spring:
  application:
    name: mediabase
#  datasource: #commenting out to deploy to cloud. Dont need local mysql databases there.
#    url: jdbc:mysql://localhost:3306/media?useSSL=false&user=root&password=password
#
#  jpa:
#    generate-ddl: true
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  com.example.mediabase.podcastsui: DEBUG

histrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#movies.ms.url: http://localhost:8081/movies   #Commenting out for implementing service-registry
#podcasts.ms.url: http://localhost:8082/podcasts